// Create Action Constants
export  enum CustomerActionTypes {
    GET_ALL_CUSTOMER = 'GET_ALL_CUSTOMER',
    UPDATE_CUSTOMER = 'UPDATE_CUSTOMER',
    DELETE_CUSTOMER = 'DELETE_CUSTOMER',
    UPDATE_SEARCH_FILTER = 'UPDATE_SEARCH_FILTER',
    CREATE_CUSTOMER = 'CREATE_CUSTOMER'

}